version: '3.8'

services:
  server:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - ACCESS_TOKEN_SECRET_KEY=$ACCESS_TOKEN_SECRET_KEY
      - REFRESH_TOKEN_SECRET_KEY=$REFRESH_TOKEN_SECRET_KEY
      - SMTP_PORT=$SMTP_PORT
      - SMTP_HOST=$SMTP_HOST
      - SMTP_USER=$SMTP_USER
      - SMTP_PASS=$SMTP_PASS
      - STRIPE_PUBLIC_KEY=$STRIPE_PUBLIC_KEY
      - STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
      - API_URL=$API_URL
      - CLIENT_URL=$CLIENT_URL
      - PORT=$PORT
      - DB_URL=$DB_URL
    restart: always
    ports:
      - '5000:5000'
      - '9229:9229'
    volumes:
      - ./dist:/app/dist
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdatacloud:/data/db

volumes:
  dbdatacloud: